version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - API_URL=http://localhost:3000
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=flight_management
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - JWT_SECRET=your_secure_jwt_secret_key
    restart: always

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flight_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  postgres_data:
